name: Transleer
version: '${version}'
main: me.albedim.transleer.Transleer
api-version: '1.18'
commands:
  messages:
    aliases:
      - msgs:
        description: Show all messages
        usage: /msgs
  translate:
    aliases:
      - tr:
          description: Translate a message
          usage: /tr <username:messageIndex> <language>
